version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha92423542
      MYSQL_DATABASE: clientes
      MYSQL_USER: izaias
      MYSQL_PASSWORD: senha92423542
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - minha-rede

  backend:
    build: .
    container_name: backend_api
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://izaias:senha92423542@db:3306/clientes
      PORT: 5000
      HOST: 0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    networks:
      - minha-rede
    command: npm run dev  # ou o comando para rodar seu backend

networks:
  minha-rede:
    driver: bridge
